### ISSUE TITLE
Gap with jquery.floatThead and margins

### ISSUE THREAD

**Issue by haxney** [rweng/jquery-datatables-rails#85]
I am getting a gap between the top of the table header and the top of the viewport when using the [floatThead](http://mkoryak.github.io/floatThead/) plugin. See the screenshot below:

![screenshot from 2014-01-24 00 43 27](https://f.cloud.github.com/assets/88132/1992405/6b3f089a-84bc-11e3-8f03-d59963288caa.png)

I tracked the problem down to the presence of `!important` declarations in `jquery.dataTables.bootstrap3.css.scss`, line 44:

``` css
table.dataTable {
        clear: both;
        margin-top: 6px !important;
        margin-bottom: 6px !important;
        max-width: none !important;
}
```

This prevents the table from moving all the way to the top of the screen. Is there any reason why this is needed?
