### ISSUE TITLE
Scroller not working on Responsive Installation

### ISSUE THREAD

**Issue by uhn-nohn** [rweng/jquery-datatables-rails#88]
Hello,

I am trying to implement the infinite scrollY.
I required the plugin in application.js
`//= require dataTables/extras/Scroller`

Here is my code:

```
tC = $('#keys')
tC.dataTable
    bJQueryUI: true
    bAutoWidth: false
    bStateSave: false
    sScrollY: "400px"
    sAjaxSource: $('#keys').data('source')
    bServerSide: true
    sDom: "frtiS"
    oScroller:
        loadingIndicator: true
    fnPreDrawCallback: ->
        responsiveHelper = new ResponsiveDatatablesHelper(tC, breakpointDefinition) unless        responsiveHelper
    fnRowCallback: (nRow, aData, iDisplayIndex, iDisplayIndexFull) ->
        responsiveHelper.createExpandIcon nRow
    fnDrawCallback: (oSettings) ->
        responsiveHelper.respond()`
```

When I add the sScrollY: "400px" the table start to brake, and the responsive side of it is not working at all(no column is hiding, and at resize the column header doesn't resize)

Thank you
